//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameraVote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameraVote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddVoteOptionWindow_Add {
            get {
                return ResourceManager.GetString("AddVoteOptionWindow_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot signed..
        /// </summary>
        public static string Backend_BallotSigned {
            get {
                return ResourceManager.GetString("Backend_BallotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign &apos;:&apos; is not allowed..
        /// </summary>
        public static string Backend_ColonNotAllowed {
            get {
                return ResourceManager.GetString("Backend_ColonNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username..
        /// </summary>
        public static string Backend_EnterUsername {
            get {
                return ResourceManager.GetString("Backend_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string Backend_LoginFailed {
            get {
                return ResourceManager.GetString("Backend_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfull..
        /// </summary>
        public static string Backend_LoginSuccessfull {
            get {
                return ResourceManager.GetString("Backend_LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is weak..
        /// </summary>
        public static string Backend_PasswordIsWeak {
            get {
                return ResourceManager.GetString("Backend_PasswordIsWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes accepted..
        /// </summary>
        public static string Backend_VotesAccepted {
            get {
                return ResourceManager.GetString("Backend_VotesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ballot it is:.
        /// </summary>
        public static string Backend_YourBallotIdIs {
            get {
                return ResourceManager.GetString("Backend_YourBallotIdIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginWindow_Login {
            get {
                return ResourceManager.GetString("LoginWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginWindow_Password {
            get {
                return ResourceManager.GetString("LoginWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginWindow_Username {
            get {
                return ResourceManager.GetString("LoginWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string MainWindow_Configuration {
            get {
                return ResourceManager.GetString("MainWindow_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MainWindow_Login {
            get {
                return ResourceManager.GetString("MainWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyVotings.
        /// </summary>
        public static string MainWindow_MyVotings {
            get {
                return ResourceManager.GetString("MainWindow_MyVotings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MainWindow_Register {
            get {
                return ResourceManager.GetString("MainWindow_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string MainWindow_Vote {
            get {
                return ResourceManager.GetString("MainWindow_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add option.
        /// </summary>
        public static string NewVotingWindow_AddOption {
            get {
                return ResourceManager.GetString("NewVotingWindow_AddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unregistered users.
        /// </summary>
        public static string NewVotingWindow_AllowUnregisteredUsers {
            get {
                return ResourceManager.GetString("NewVotingWindow_AllowUnregisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string NewVotingWindow_Anonymous {
            get {
                return ResourceManager.GetString("NewVotingWindow_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum options.
        /// </summary>
        public static string NewVotingWindow_MaximumOptions {
            get {
                return ResourceManager.GetString("NewVotingWindow_MaximumOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string NewVotingWindow_Password {
            get {
                return ResourceManager.GetString("NewVotingWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewVotingWindow_Title {
            get {
                return ResourceManager.GetString("NewVotingWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string NewVotingWindow_Upload {
            get {
                return ResourceManager.GetString("NewVotingWindow_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PrintWindow_Language {
            get {
                return ResourceManager.GetString("PrintWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintWindow_Print {
            get {
                return ResourceManager.GetString("PrintWindow_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterWindow_Password {
            get {
                return ResourceManager.GetString("RegisterWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterWindow_Register {
            get {
                return ResourceManager.GetString("RegisterWindow_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string RegisterWindow_Token {
            get {
                return ResourceManager.GetString("RegisterWindow_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RegisterWindow_Username {
            get {
                return ResourceManager.GetString("RegisterWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Voting.
        /// </summary>
        public static string UserVotingsWindow_AddNewVoting {
            get {
                return ResourceManager.GetString("UserVotingsWindow_AddNewVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UserVotingsWindow_MenuItem_Delete {
            get {
                return ResourceManager.GetString("UserVotingsWindow_MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string VerifyWindow_Signature {
            get {
                return ResourceManager.GetString("VerifyWindow_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyWindow_Verify {
            get {
                return ResourceManager.GetString("VerifyWindow_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote ID.
        /// </summary>
        public static string VerifyWindow_VoteID {
            get {
                return ResourceManager.GetString("VerifyWindow_VoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string VotingResultsWindow_Print {
            get {
                return ResourceManager.GetString("VotingResultsWindow_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum results.
        /// </summary>
        public static string VotingResultsWindow_Sum {
            get {
                return ResourceManager.GetString("VotingResultsWindow_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VotingResultsWindow_Verify {
            get {
                return ResourceManager.GetString("VotingResultsWindow_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting users.
        /// </summary>
        public static string VotingSumResultsWindow_Clients {
            get {
                return ResourceManager.GetString("VotingSumResultsWindow_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unregistered users.
        /// </summary>
        public static string VotingWindow_AllowUnregisteredUsers {
            get {
                return ResourceManager.GetString("VotingWindow_AllowUnregisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string VotingWindow_Anonymous {
            get {
                return ResourceManager.GetString("VotingWindow_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download voting.
        /// </summary>
        public static string VotingWindow_DownloadVoting {
            get {
                return ResourceManager.GetString("VotingWindow_DownloadVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ballot.
        /// </summary>
        public static string VotingWindow_GetBallot {
            get {
                return ResourceManager.GetString("VotingWindow_GetBallot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string VotingWindow_GetSignature {
            get {
                return ResourceManager.GetString("VotingWindow_GetSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum options.
        /// </summary>
        public static string VotingWindow_MaximumOptions {
            get {
                return ResourceManager.GetString("VotingWindow_MaximumOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string VotingWindow_Password {
            get {
                return ResourceManager.GetString("VotingWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address: .
        /// </summary>
        public static string VotingWindow_ServerAddress {
            get {
                return ResourceManager.GetString("VotingWindow_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string VotingWindow_Username {
            get {
                return ResourceManager.GetString("VotingWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string VotingWindow_Vote {
            get {
                return ResourceManager.GetString("VotingWindow_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting ID.
        /// </summary>
        public static string VotingWindow_VotingID {
            get {
                return ResourceManager.GetString("VotingWindow_VotingID", resourceCulture);
            }
        }
    }
}
